name: Build PLP Linux (Executable)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            ffmpeg \
            libgl1 \
            libxcb-xinerama0 \
            libxkbcommon-x11-0

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build PLP with PyInstaller
        run: |
          pyinstaller \
            --noconfirm \
            --clean \
            --onefile \
            --windowed \
            --name "plp2.1" \
            --icon=plp_logo.ico \
            --hidden-import=PyQt6 \
            --hidden-import=PyQt6.QtCore \
            --hidden-import=PyQt6.QtGui \
            --hidden-import=PyQt6.QtWidgets \
            --hidden-import=PyQt6.QtMultimedia \
            --hidden-import=PyQt6.QtMultimediaWidgets \
            --hidden-import=PyQt6.QtSvg \
            --collect-all PyQt6 \
            --add-data "plp_logo.ico:." \
            --add-data "plp_logo.png:." \
            --add-data "fonts:fonts" \
            --add-data "icons:icons" \
            plp2.1.py

      - name: Make binary executable
        run: |
          chmod +x dist/plp2.1

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: plp-2.1-linux-x64
          path: dist/plp2.1
